### PR TITLE
Add UMAP embedding visualisation script

### PR DESCRIPTION
**Pull request by amorehead**
* Adds a `visualise.py` script that lets one load any pre-trained encoder checkpoint, embed an entire dataset as a collection of graph embeddings, and then plot the collected embeddings using a Gaussian flavour of UMAP.
* Lists the top 20 most common label string values in the legend of the resulting figure. For example, when running this script with the settings `python proteinworkshop/visualise.py ckpt_path=$MY_PT_CA_BB_CKPT_PATH plot_filepath=output_visualisations/pt_encoder_fold_superfamily.png dataset=fold_superfamily encoder=gcpnet features=ca_bb task=multiclass_graph_classification`, this yields the top 20 most common superfamilies being identified in the figure's legend.
* Plots may be adjusted as desired by the user. The core logic for acquiring dataset graph embeddings is provided (i.e., batteries included).

### CODE REVIEW

**Comment by amorehead** [comment]
I am currently facing an odd indexing error when I run for the full `fold_superfamily` dataset. On a subset of the dataset, I am seeing clusterings such as the following, for reference.

structure_denoising_pretrained_gcpnet_fold_superfamily

**Comment by amorehead** [comment]
One idea for quantifying each encoder's clustering ability would be to report each method's Dunn Index and Silhouette value.

**Comment by a-r-j** [comment]
How are devices handled? Normally the `L.Trainer` would handle this but we're not using that here. I suppose this is all happening on the CPU?

**Comment by amorehead** [comment]
Great point. I completely missed that the trainer wasn't being instantiated here. No wonder my initial runs of the script were so slow. In [this commit](https://github.com/a-r-j/ProteinWorkshop/pull/55/commits/50ae9a0dea4dbfe2b17eec8a9179fcf2db20c06f), I've added GPU support for both `embed.py` and `visualise.py`. Moreover, after timing `visualise.py` with GCPNet on the `fold_superfamily` dataset, I was able to create the plot below in around 4 minutes using a GPU.

structure_denoising_pretrained_gcpnet_fold_superfamily

**Pull request merged**
